"""The vendored _common/ copies must match the canonical shared source.

Shared connector code is copied into each plugin because the Hermes plugin
loader roots a plugin package at its own directory -- sibling packages are
not importable.  Copies are generated by scripts/sync_shared.py and must
never be hand-edited; this test is what makes that enforceable.
"""

from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
CANONICAL = REPO / "shared" / "ericsson_common"
PLUGINS = REPO / "plugins"

# Connectors that consume the shared transport. ericsson-teams is excluded:
# it is Graph-only and has no REST client to share.
CONSUMERS = ["ericsson-jira", "ericsson-gitlab"]


def _canonical_files():
    return sorted(p.relative_to(CANONICAL) for p in CANONICAL.rglob("*.py"))


def test_canonical_source_exists():
    assert CANONICAL.is_dir(), f"missing canonical shared source at {CANONICAL}"
    assert (CANONICAL / "__init__.py").is_file()


@pytest.mark.parametrize("plugin", CONSUMERS)
def test_copy_has_every_canonical_file(plugin):
    vendored = PLUGINS / plugin / "_common"
    assert vendored.is_dir(), (
        f"{plugin} has no _common/ -- run: python scripts/sync_shared.py"
    )
    missing = [
        str(rel) for rel in _canonical_files() if not (vendored / rel).is_file()
    ]
    assert not missing, (
        f"{plugin}/_common is missing {missing} -- "
        f"run: python scripts/sync_shared.py"
    )


@pytest.mark.parametrize("plugin", CONSUMERS)
def test_copy_is_byte_identical(plugin):
    vendored = PLUGINS / plugin / "_common"
    drifted = [
        str(rel)
        for rel in _canonical_files()
        if (vendored / rel).is_file()
        and (vendored / rel).read_bytes() != (CANONICAL / rel).read_bytes()
    ]
    assert not drifted, (
        f"{plugin}/_common has hand-edited files: {drifted}. "
        f"Edit shared/ericsson_common/ instead, then run "
        f"python scripts/sync_shared.py"
    )


@pytest.mark.parametrize("plugin", CONSUMERS)
def test_copy_has_no_extra_files(plugin):
    vendored = PLUGINS / plugin / "_common"
    canonical = set(_canonical_files())
    extra = [
        str(p.relative_to(vendored))
        for p in vendored.rglob("*.py")
        if p.relative_to(vendored) not in canonical
    ]
    assert not extra, f"{plugin}/_common has stale files: {extra}"
